language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
osx_image: xcode7.3
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl nginx; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; else ./install-nginx.sh; fi
install:
  - export PATH="$PATH:$HOME/nginxinstall/sbin/"
before_script:
  - npm install -g bower
  - npm install -g gulp
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh
notifications:
  webhooks:
    secure: "VASW9+87Yl4roIDDw/+4DZYCIqAzdATEk4w52TIWDdG1mmqV1Z83Iol2sQdAViUctXzxIto/OibCGzBlsUFp8J+J6Yw+BOng4jrOTbFMguQw+/UMhRmtLIMu/eWJMiFr7Homjan5owu1TZmfIkR8XYxXyeY4ITJqJkkDmq53eHE="
  on_success: always
  on_failure: always
  on_start: always
